[package]
name = "zpr-ext"
version = "0.5.3"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bytes = { workspace = true, optional = true }
libc = { workspace = true }
nix = { workspace = true, features = ["ioctl", "net", "socket"] }
socket2 = { workspace = true, optional = true }
tokio = { workspace = true, features = ["net"], optional = true }
zerocopy = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "rt"] }

[features]
# Each feature flag is the name of a library the user is already using
# and would like to have "extended".
all = ["bytes", "socket2", "tokio", "zerocopy"]
bytes = ["dep:bytes"]
socket2 = ["dep:socket2"]
tokio = ["dep:tokio"]
zerocopy = ["dep:zerocopy"]
