name: Rust-cbpfrs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cbpf-rs/**'
      - '.github/workflows/cbpfrs.yml'
  pull_request:
    paths:
      - 'cbpf-rs/**'
      - '.github/workflows/cbpfrs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cbpf-build:
    name: CBPF
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@v1
    with:
      name: 'CBPF'
      path: './cbpf-rs'
      runs-on: "['ubuntu-latest']"
      needs-libpcap: true
    secrets: 
      ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}