name: Rust-zprext

on:
  push:
    branches: [ "main" ]
    paths:
      - 'zpr-ext/**'
      - '.github/workflows/zprext.yml'
  pull_request:
    paths:
      - 'zpr-ext/**'
      - '.github/workflows/zprext.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  zpr-ext:
    name: ZPR Ext
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@v1.2
    with:
      name: 'ZPR-Ext'
      path: './zpr-ext'
      features: 'all'
    secrets: 
      ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}
